# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration                               +
# project    nord-visual-studio-code                                     +
# repository https://github.com/arcticicestudio/nord-visual-studio-code  +
# author     Arctic Ice Studio                                           +
# email      development@arcticicestudio.com                             +
# copyright  Copyright (C) 2017                                          +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI Documentation
#   (https://docs.travis-ci.com)
language: node_js
dist: trusty
sudo: false
node_js:
  - "4"
  - "6"
  - "7"
before_install:
  - rm -rf ./node_modules
before_script:
  - npm install -g gulp-cli
  - npm install gulp
  - npm install
script:
  - gulp --harmony lint
